Gym/Controllers/AcccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Gym.Models.Entity;
using Gym.Models.Manager;
namespace Gym.Controllers
{
    public class AcccountController : Controller
    {
        // GET: Acccount
        public ActionResult Index()
        {
            return View();
        }

    

       [HttpPost]
        public ActionResult Index(UserEntity detail)
        {
            UserEntity entity = new UserEntity();
            if (detail.Type == "Admin")
            {
                entity = ManagerAcccount.ValidateAdminUser(detail);

                if (!string.IsNullOrEmpty(entity.id))
                {
                    FormsAuthentication.SetAuthCookie(entity.id, false);

                    var authTicket = new FormsAuthenticationTicket(1, entity.id, DateTime.Now, DateTime.Now.AddMinutes(120), false, entity.Roles);
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    return RedirectToAction("Index", "Home");
                }
            }
            else if (detail.Type == "Member")
            {
                entity = ManagerAcccount.ValidateMemberUser(detail);

                if (!string.IsNullOrEmpty(entity.id))
                {
                    FormsAuthentication.SetAuthCookie(entity.id, false);

                    var authTicket = new FormsAuthenticationTicket(1, entity.id, DateTime.Now, DateTime.Now.AddMinutes(120), false, entity.Roles);
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                   
                    return RedirectToAction("Index", "Home");
                }
            }
           

            ModelState.AddModelError("", "Invalid login attempt.");
            return View(detail);
        }
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Gym/Controllers/HomeController.cs
//HomeController

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gym.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: Home
        [Authorize(Roles ="Admin,Member")]
        public ActionResult Index()
        {
            
            return View();
        }
        [Authorize(Roles ="Member")]
       public ActionResult MemberIndex()
        {
            return View();
        }
        
    }
}

Gym/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_mainlayout.cshtml";
}

<h2 style="padding-left:200px">Fitness Management System</h2>

Gym/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_mainlayout.cshtml";
}

<div class="col-sm-12 col-md-12 col-lg-12">
	<div class="widget-bg-color-icon card-box">
		WELCOME TO THE GYM SYSTEM
	</div>
</div>

Gym/Views/Home/MemberIndex.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
	<meta name="author" content="Coderthemes">

	<link rel="shortcut icon" href="assets/images/favicon_1.ico">

	<title>GYM SYS</title>

	<!--Morris Chart CSS -->
	<link rel="stylesheet" href="/Content/assets/plugins/morris/morris.css">
	<link href="/Content/assets/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet" type="text/css">

	<link href="/Content/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="/Content/assets/css/core.css" rel="stylesheet" type="text/css" />
	<link href="/Content/assets/css/components.css" rel="stylesheet" type="text/css" />
	<link href="/Content/assets/css/icons.css" rel="stylesheet" type="text/css" />
	<link href="/Content/assets/css/pages.css" rel="stylesheet" type="text/css" />
	<link href="/Content/assets/css/responsive.css" rel="stylesheet" type="text/css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Style/StyleSheet1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <table class="wrapper" cellpadding="0" cellspacing="0">
        <tr>
            <td colspan="3" class="header"> FITNESS CLUB</td>
        </tr>
        <tr>
            <td class="leftplan">
                <table cellpadding="0" cellspacing="0" style="width:100%">
                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Home", "Index", "Home", null, new { @class = "plan" })
                        </td>
                    </tr>
                   
                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Trainer", "Index", "Trainer", null, new { @class = "plan" })
                        </td>
                    </tr>
                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Plan", "Index", "Plan", null, new { @class = "plan" })
                        </td>
                    </tr>
                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Equipment", "Index", "Equipment", null, new { @class = "plan" })
                        </td>
                    </tr>

                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Customer", "Index", "Customer", null, new { @class = "plan" })
                        </td>
                    </tr>

                    <tr>
                        <td class="plancell">
                            @Html.ActionLink("Logout", "LogOff", "Acccount", null, new { @class = "plan" })
                        </td>
                    </tr>



                </table>
            </td>
            <td class="container">
                <h1>Member Page</h1>
               
            </td>
        </tr>
        <tr>
            <td colspan="3" class="footer">&copy;Fitness Club 2018</td>
        </tr>
    </table>
</body>
</html>